services:
  web:
    container_name: aniwrap-backend
    image: "ghcr.io/cs-gang/aniwrap-backend:latest"
    environment:
    - ANIWRAP_DEBUG=false
    - ANIWRAP_DATABASE_URL=postgresql+asyncpg://aniwrap:aniwrap@postgres:5432/aniwrapdb
    # Add remaining required environment variables here
    # See .env.example for list of variables
    # Or, set all env vars in a .env file and then use the
    # env_file key here intead of `environment`
    # See: https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-env_file-attribute
    ports: 
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    container_name: aniwrap-postgres
    image: "postgres:17-alpine"
    environment:
      - POSTGRES_USER=aniwrap
      - POSTGRES_PASSWORD=aniwrap
      - POSTGRES_DB=aniwrapdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aniwrap -d aniwrapdb" ]
      interval: 2s
      timeout: 1s
      retries: 5
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

volumes:
  postgres_data: