# .github/workflows/publish-to-ghcr.yml

name: Build and Publish to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Extract version using Python
        id: get_version
        shell: python
        run: |
          import tomllib
          import os

          with open('pyproject.toml', 'rb') as f:
              data = tomllib.load(f)

          version = data['project']['version']
          print(f"Version found: {version}")

          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              print(f"version={version}", file=f)

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ GITHUB_REPOSITORY }}:latest
            ghcr.io/${{ GITHUB_REPOSITORY }}:${{ steps.get_version.outputs.version }}
          build-args: |
            APP_VERSION=${{ steps.get_version.outputs.version }}